#!/usr/bin/env bash
set -euo pipefail

require_env() {
  local var_name="$1"
  if [ -z "${!var_name:-}" ]; then
    echo "Missing required environment variable: ${var_name}" >&2
    exit 1
  fi
}

require_env "GITHUB_OUTPUT"
require_env "BRANCH"
require_env "STRATEGY"
require_env "ARTIFACT_DIR"
require_env "WORKFLOW_RUN_ID"
require_env "WORKFLOW_REPOSITORY"

CONFLICT_COUNT=${CONFLICT_COUNT:-0}
REBASE_RESULT=${REBASE_RESULT:-n/a}
MERGE_RESULT=${MERGE_RESULT:-n/a}

resolution_file="${ARTIFACT_DIR}/conflict_resolution.log"
conflict_file="${ARTIFACT_DIR}/conflicts.txt"

if [ -s "$resolution_file" ]; then
  RESOLUTION_LINES=$(sed 's/^/- /' "$resolution_file")
else
  RESOLUTION_LINES="- No conflicts detected"
fi

if [ -s "$conflict_file" ]; then
  CONFLICT_LINES=$(sed 's/^/- /' "$conflict_file")
else
  CONFLICT_LINES="- None"
fi

body_file="pr_body.md"
cat <<EOF > "$body_file"
## Summary
- Upstream sync executed on $(date -u +"%Y-%m-%d %H:%M UTC")
- Branch: ${BRANCH}
- Strategy: ${STRATEGY}
- Rebase result: ${REBASE_RESULT}
- Merge result: ${MERGE_RESULT}
- Conflicts detected: ${CONFLICT_COUNT}

## Conflict Resolution Summary
${RESOLUTION_LINES}

## Remaining Conflicts
${CONFLICT_LINES}

## Validation
- [x] Tests (with Docker/PostgreSQL) — workflow run ${WORKFLOW_RUN_ID}
- [x] Tests (without Docker)
- [x] Race detector suite

## Feature Flags
- `enable_guarded_stop_loss`: default ON (unchanged)
- `enable_mutex_protection`: default ON (unchanged)
- `enable_persistence`: default ON (unchanged)
- `enable_risk_enforcement`: default ON (unchanged)

## Persistence
- PostgreSQL-backed persistence validated in Docker matrix job.
- Queue-based risk persistence remains guarded by `enable_persistence`.
- Failures remain non-fatal, preserving trading continuity.

## Deployment Checklist
- [x] Sync branch pushed: `${BRANCH}`
- [x] Diff report generated (see workflow artifacts)
- [x] Automated test matrix green
- [ ] Manual review of DIFF_REPORT.md
- [ ] Monitor feature flag telemetry after deploy

## Artifacts
- `DIFF_REPORT.md`
- `conflict_resolution.log`
- `conflicts.txt`

Generated by workflow run [${WORKFLOW_RUN_ID}](https://github.com/${WORKFLOW_REPOSITORY}/actions/runs/${WORKFLOW_RUN_ID}).
EOF

echo "body_path=${body_file}" >> "$GITHUB_OUTPUT"
